from setuptools import setup, find_packages

setup(
    name="bcc-detection",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "tensorflow>=2.8.0",
        "scikit-learn>=1.0.0",
        "scikit-image>=0.19.0",
        "opencv-python>=4.5.0",
        "tifffile>=2021.11.0",
        "pandas>=1.3.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "jupyter>=1.0.0",
        "pytest>=6.2.0",
        "black>=21.12b0",
        "flake8>=4.0.0",
        "mypy>=0.910",
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="A deep learning system for Basal Cell Carcinoma detection",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/bcc-detection",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
    python_requires=">=3.8",
) 